### PR TITLE
Issue 3

### LINKED ISSUE #3: Sync Command
Sync stopped tasks
1. Get stopped tasks
2. Sync wotklog time to Jira server
3. Mark failed/not-found tasks as failed and report them back

Command format
```bash
php jiralogger log:sync
```

### PR DESCRIPTION
**Pull request by mohamed-abdul-fattah**
Sync command with updates to connect command

### CODE REVIEW

File: src/Http/Request.php [hunk 1]
```diff
@@ -103,14 +122,36 @@ public function json(
...
-            $uri,
-            [
-                'headers' => $headers,
-                'json'    => $params,
-            ]
-        );
+        $jar = null;
+        if (! empty($this->sessionId)) {
+            $jar = new CookieJar;
+            $jar = $jar->fromArray(['JSESSIONID' => $this->sessionId], 'jira.espace.ws');
```
Comment (mohamed-abdul-fattah) [inline src/Http/Request.php]: Jira URI should be dynamic. Use `$this->baseUri`

**Review by mohamed-abdul-fattah — COMMENTED** [review]
LGTM
